#!/bin/bash

# Shared runtime helpers for the native Slurm workflow.

workflow_die() {
	echo "ERROR: $*" >&2
	exit 1
}

require_uint() {
	case "$1" in
		''|*[!0-9]*) workflow_die "$2 must be an unsigned integer (got '$1')" ;;
	esac
}

load_run_env() {
	local requested_dir=${1:-.}

	requested_dir=$(cd "$requested_dir" 2>/dev/null && pwd) || \
		workflow_die "run directory not found: $requested_dir"
	[ -f "$requested_dir/run.env" ] || workflow_die "run.env not found in $requested_dir"

	set -a
	# run.env is generated by setUpRun.sh from the trusted run configuration.
	# shellcheck disable=SC1090
	. "$requested_dir/run.env"
	set +a

	[ -n "${modelDir:-}" ] || workflow_die "modelDir is missing from run.env"
	[ -n "${yearStart:-}" ] || workflow_die "yearStart is missing from run.env"
	[ -n "${yearEnd:-}" ] || workflow_die "yearEnd is missing from run.env"
	[ -n "${toolkitDir:-}" ] || workflow_die "toolkitDir is missing from run.env"

	modelDir=$(cd "$modelDir" 2>/dev/null && pwd) || workflow_die "modelDir not found: $modelDir"
	export modelDir
}

mark_task() {
	local year=$1
	local task=$2
	local state_dir="$modelDir/state/$year"
	local target="$state_dir/$task.ok"
	local tmp="$state_dir/.$task.ok.$$"

	mkdir -p "$state_dir"
	{
		printf 'task=%s\n' "$task"
		printf 'year=%s\n' "$year"
		printf 'job_id=%s\n' "${SLURM_JOB_ID:-manual}"
		printf 'completed_at=%s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
	} > "$tmp"
	mv -f "$tmp" "$target"
}

activate_netcdf_environment() {
	local restore_nounset=0
	case $- in *u*) restore_nounset=1; set +u ;; esac

	# shellcheck disable=SC1091
	. /etc/profile
	module add gcc netcdf/4.7.4/parallel/gcc-openmpi \
		hdf5/1.10.6/gcc-openmpi mpi/openmpi/4.0.3/gcc/ib perl

	[ "$restore_nounset" -eq 1 ] && set -u
}

activate_analysis_environment() {
	local restore_nounset=0
	local hook
	case $- in *u*) restore_nounset=1; set +u ;; esac

	# shellcheck disable=SC1091
	. /etc/profile
	module add gcc netcdf/4.7.4/parallel/gcc-openmpi \
		hdf5/1.10.6/gcc-openmpi mpi/openmpi/4.0.3/gcc/ib perl
	module add ferret/7.6.0

	: "${MAMBA_EXE:=/gpfs/home/vhf24tbu/miniforge3/bin/mamba}"
	: "${MAMBA_ROOT_PREFIX:=/gpfs/home/vhf24tbu/miniforge3}"
	: "${analysisEnv:=base}"
	[ -x "$MAMBA_EXE" ] || workflow_die "mamba executable not found: $MAMBA_EXE"
	hook=$("$MAMBA_EXE" shell hook --shell bash --root-prefix "$MAMBA_ROOT_PREFIX")
	eval "$hook"
	mamba activate "$analysisEnv"

	[ "$restore_nounset" -eq 1 ] && set -u
}
