#!/bin/sh
#SBATCH -p compute
#SBATCH -t 06:00:00 
#SBATCH --job-name=tidyup
#SBATCH -o tidy-%j.log
#SBATCH -e tidy-%j.log  
#SBATCH --mem 64G

echo "Tidying up: " $modelDir $yearToTidy $Model

module add gcc netcdf/4.7.4/parallel/gcc-openmpi hdf5/1.10.6/gcc-openmpi mpi/openmpi/4.0.3/gcc/ib perl
module add ferret/7.6.0

export MAMBA_EXE='/gpfs/home/vhf24tbu/miniforge3/bin/mamba'
export MAMBA_ROOT_PREFIX='/gpfs/home/vhf24tbu/miniforge3'
__mamba_setup="$("$MAMBA_EXE" shell hook --shell bash --root-prefix "$MAMBA_ROOT_PREFIX" 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__mamba_setup"
else
    alias mamba="$MAMBA_EXE"
fi
unset __mamba_setup

mamba activate base

cd $modelDir

./tidyup.sh $yearToTidy $yearToTidy $Model $basedir
